name: CI

on:
  pull_request:
  push:
    branches:
      - main
    tags: ["*"]

permissions:
  contents: read

jobs:
  lint:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0

      - run: npm ci

      - name: Prettier
        run: |
          npx prettier --check .

      - name: eslint
        run: |
          npx eslint

  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0

      - run: npm ci

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test
